version: '3'

services:
  medall-landing:
    container_name: medall_landing
    build: .
    restart: unless-stopped
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefiknet"
      - "traefik.http.routers.medall-landing.rule=Host(`medall.ca`) && PathPrefix(`/`)"
      - "traefik.http.routers.medall-landing.middlewares=medall-landing-strip"
      - "traefik.http.routers.medall-landing.tls=true"
      - "traefik.http.routers.medall-landing.tls.certresolver=letsencrypt"
      - "traefik.http.middlewares.medall-landing-strip.stripprefix.prefixes=/"
      - "traefik.http.routers.medall-landing.entrypoints=websecure"
      - "traefik.http.services.medall-landing.loadbalancer.server.port=80"

networks:
  traefiknet:
    external: true
